server:
  port: 9001
  
spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: study
      port: 27017
      host: localhost
      auto-index-creation: true # 

